//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DLEVEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class News
    {
       
        public int news_ID { get; set; }

        public string user_id { get; set; }

        [Required(ErrorMessage = "Please enter a title")]
        [DisplayName("Title")]
        [StringLength(50)]
        public string title { get; set; }

        // [DataType(DataType.Date)]
        [DisplayName("Date of Pub")]
        public System.DateTime datePub { get; set; }
        [DisplayName("Comment")]
        [StringLength(200)]
        public string comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
