//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLEVEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public partial class Staff
    {
        [Required(ErrorMessage = "Please enter a Staff Name")]
        [DisplayName("Staff Name")]
        [StringLength(50)]
        public string staff_Name { get; set; }

        [Required(ErrorMessage = "Please enter a Company Name")]
        [DisplayName("Company Name")]
        [StringLength(50)]
        public string company_Name { get; set; }

        [Required(ErrorMessage = "Please enter an Address")]
        [DisplayName("Address")]
        [StringLength(199)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter a phone number")]
        [DisplayName("Contact Number")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        [StringLength(50)]
        public string phone { get; set; }

        [Required(ErrorMessage = "Please enter an Email")]
        [DisplayName("Email")]
        [StringLength(50)]
        public string email { get; set; }

        [Required(ErrorMessage = "Please enter an age")]
        [DisplayName("Age")]
        [Range(1, 150, ErrorMessage = "The value must be greater than 1 and less than 150")]

        public Nullable<int> age { get; set; }
        public string user_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
